In [1]:
import numpy

In [2]:
n = numpy.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
print(n) # print in a nice form

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [5]:
n.reshape(3,9) #convert in two dimensional array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
n.reshape(3,3,3) #three dimensional array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
type(n) # It is not a list!

numpy.ndarray

In [10]:
m = numpy.asarray([[123,12,123,12,33],[],[]])

D:\anaconda\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


In [12]:
type(m)

numpy.ndarray

**Numpy** is a base library for all the libraries. Numpy is simple and low level of storing data but requirments of many other libraries like pandas.

## 1. convert image to numpy using cv2

In [14]:

import cv2

In [15]:
im_g = cv2.imread("smallgray.png",0) # 0 means you want to read image in 
#grey scale, with 1 you are reading image in BGR
im_g # two dimensional array
# 0 is black and 255 is white. between them is other colours

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
im_g = cv2.imread("smallgray.png",0)
print(im_g)
# first group is blue, second is green, third one is red.

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [18]:
cv2.imwrite("newsmallgray.png",im_g) # True > your file has been created

True

## 2. Indexing, Slicing, Iterating

In [19]:
a = [1,2,3]

In [20]:
a[0:2]

[1, 2]

In [24]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [25]:
im_g.shape

(3, 5)

In [26]:
im_g[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [27]:
im_g[2,4]

182

In [28]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [29]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [30]:
for i in im_g.flat: # it allows to access the values one by one.
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


## 3. Stacking(Concatenating) and Splitting

In [31]:
ims = numpy.hstack(im_g,im_g)    #horisontal stack
# we can't just pass two arguments
# we need to use tuples

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [37]:
ims = numpy.hstack((im_g,im_g,im_g))

In [38]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [39]:
ims = numpy.vstack((im_g,im_g,im_g)) #vertical stack

In [40]:
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [41]:
lst = numpy.hsplit(ims,3) # how many split horizontally
# but in this case, Numpy doesn't know how to split

ValueError: array split does not result in an equal division

In [42]:
lst = numpy.hsplit(ims,5) 
# 5 split has only one way to do it so it can be executed

In [43]:
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [45]:
lst=numpy.vsplit(ims,3)

In [46]:
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [47]:
type(lst) #type of numpy array is list

list